version: "3.9"
services:
  workerdisk:
    build: .
    environment:
      - API_ID=16734393
      - API_HASH=${HASH}
      - TOKEN=${TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
